all: 
	g++ -Wall -g cartesianTest.cpp -lgtest_main  -lgtest -lpthread -o ctest 
	g++ -Wall -g averageSolutionTest.cpp -lgtest_main  -lgtest -lpthread -o avstest
	g++ -Wall -g functionTest.cpp -lgtest_main  -lgtest -lpthread -o ftest 
